### PR TITLE
env variable file support

### LINKED ISSUE #322: Secret support for email || maybe email issue
Hello, could you please add secret support for:

-       EMAIL_FROM_ADDRESS_FILE: /run/secrets/email_user
-       SMTP_USERNAME_FILE: /run/secrets/email_user
-       SMTP_PASSWORD_FILE: /run/secrets/email_password

Thanks a lot

### LINKED ISSUE #389: Docker Compose secrets not passing into env vars
After toiling with my secret files in docker compose, I realized that the contents of the secret files aren't being passed into environment variables such as WGUI_PASSWORD and SMTP_PASSWORD. Is my compose file set up correctly or is this feature not supported as of yet?

```
version: "3"

volumes:
  wireguard-ui_db:
    external: true

services:
  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    cap_add:
      - NET_ADMIN
    # required to show active clients. with this set, you don't need to expose the ui port (5000) anymore
    network_mode: host
    #ports:
    #  - ${CUSTOM_PORT}:5000
    environment:
      - SESSION_SECRET=/run/secrets/session-secret
      - WGUI_USERNAME=JohnDoe
      - WGUI_PASSWORD=/run/secrets/password

      - WGUI_ENDPOINT_ADDRESS=interesting.domain.com
      - WGUI_DNS=192.168.2.1
      #- WGUI_MTU=1450
      - WGUI_PERSISTENT_KEEPALIVE=25
      - WGUI_FIREWALL_MARK=0xca6c
      
      - WGUI_LOG_LEVEL=INFO

      - EMAIL_FROM_ADDRESS=JohnDoe@gmail.com
      - EMAIL_FROM_NAME=Wireguard UI
      - SMTP_HOSTNAME=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=JohnDoe@gmail.com
      - SMTP_PASSWORD=/run/secrets/smtp-password
      - SMTP_AUTH_TYPE=LOGIN
      - SMTP_ENCRYPTION=STARTTLS
      
      - WGUI_SERVER_INTERFACE_ADDRESSES=10.0.0.0/24
      - WGUI_SERVER_LISTEN_PORT=51820
      - WGUI_SERVER_POST_UP_SCRIPT=ufw route allow in on wg0 out on ens1; iptables -t nat -I POSTROUTING -o ens1 -j MASQUERADE; ip6tables -t nat -I POSTROUTING -o ens1 -j MASQUERADE
      - WGUI_SERVER_POST_DOWN_SCRIPT=ufw route delete allow in on wg0 out on ens1; iptables -t nat -D POSTROUTING -o ens1 -j MASQUERADE; ip6tables -t nat -D POSTROUTING -o ens1 -j MASQUERADE

      - WGUI_DEFAULT_CLIENT_ALLOWED_IPS=0.0.0.0/0
      - WGUI_DEFAULT_CLIENT_USE_SERVER_DNS=true
      - WGUI_DEFAULT_CLIENT_ENABLE_AFTER_CREATION=true

      - WGUI_MANAGE_START=false
      - WGUI_MANAGE_RESTART=false
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - wireguard-ui_db:/app/db
      - /etc/wireguard:/etc/wireguard
    secrets:
      - session-secret
      - smtp-password
    restart: unless-stopped

secrets:
    session-secret:
        file: /root/.secrets/wireguard-ui/session-secret
    smtp-password:
        file: /root/.secrets/wireguard-ui/smtp-password
```

### PR DESCRIPTION
**Pull request by cameronaw13**
Update to my previous PR fix #390 that fixes #389, fixes #322

Introduces alternatives to sensitive environment variables allowing users to pass sensitive information within a file to an environment variable to prevent the exposure of passwords and keys in the docker run command or docker compose file.

New alternative env variables include `SESSION_SECRET_FILE`, `WGUI_PASSWORD_FILE`, `WGUI_PASSWORD_HASH_FILE`, `SENDGRID_API_KEY_FILE`, and `SMTP_PASSWORD_FILE`

### CODE REVIEW

**Comment by cameronaw13** [comment]
I'm done with all the commits. Won't add any further modifications unless issues are pointed out.

**Comment by ngoduykhanh** [comment]
I personally don't think it is a good idea to have native support for loading environment variables from files as it makes the application config handling logic complicated. Also, we will have to worry about how to secure the files. To me, loading the config from environment variables directly is good enough, it works across environments such as VM, standalone docker container, Kubernetes, etc.

**Comment by cameronaw13** [comment]
Many environments such as [docker swarm](https://docs.docker.com/engine/swarm/secrets/) and [kubernetes](https://kubernetes.io/docs/concepts/configuration/secret/) offer native support for encryption that the container doesn't need to deal with when passing secret files into containers. But, outside of cluster environments, I would agree that importing secret files doesn't _really_ improve security when it acts more like a bind mount moving the potential attack surface to a different location.

On the other hand, I can't see how my implementation of config logic with file support overcomplicates things. What I've implemented are conditions in the config logic that check if a select few environment variables are empty upon startup (`SMTP_PASSWORD` for example). If so, then check if the user has provided a file in their alternative variables (`SMTP_PASSWORD_FILE`). And if both are empty, simply use a default value. To me, this change seems fairly straightforward. Maybe I could change how I implemented this in the jsondb.go file to improve the nesting but everything else seems simple enough.

But, if you see no value in adding this feature anyway due to the niche amount of people that can use it properly, then that's fair.

**Comment by qosmio** [comment]
+1 for merging this feature. I use the secret features of Docker Swarm and K8S for anything requiring passing sensitive information. It's also a pretty standard practice to use the naming connection `APP_PASS` for literal values and `APP_PASS_FILE` for extracting values.

Postres and [many other projects](https://github.com/search?q=file_env%28%29+language%3AShell&type=code&l=Shell) use the following function as part of their `init` scripts.

If you wanted to move the logic out of the `go` code you, I modified the `init.sh` script and made an inline entry for entrypoint.

```yaml
version: "3.9"

volumes:
    db:
  
secrets:
  wgui_sendgrid:
    external: true
  wgui_user:
    external: true
  wgui_pass:
    external: true

services:
  ui:
    image: ngoduykhanh/wireguard-ui
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - SENDGRID_API_KEY_FILE=/run/secrets/wgui_sendgrid
      - WGUI_USERNAME_FILE=/run/secrets/wgui_user
      - WGUI_PASSWORD_FILE=/run/secrets/wgui_pass
    volumes:
      - db:/app/db
      - /etc/wireguard:/etc/wireguard
    secrets:
      - wgui_sendgrid
      - wgui_user
      - wgui_pass
    deploy:
      placement:
        constraints:
          - node.hostname == minipc
      mode: global
    entrypoint:
      - /bin/bash
      - -c
      - |
        set -eo pipefail
        file_env() {
          local var="$1"
          local fileVar="${var}_FILE"
          local def="${2:-}"
          local val
          if [ "${!var:-}" ] && [ "${!fileVar:-}" ]; then
            printf >&2 'error: both %s and %s are set (but are exclusive)\n' "$var" "$fileVar"
            exit 1
          fi
          local val=${def}
          if [ "${!var:-}" ]; then
            val="${!var}"
          elif [ "${!fileVar:-}" ]; then
            val="$(< "${!fileVar}")"
          fi
        
          [[ "$val" != "" ]] && export "$var"="$val"
          unset fileVar
        }
        # Could technically add all variables referenced here, 
        # but for now only listing ones commonly considered sensitive
        env_file_vars=(
          SESSION_SECRET
          WGUI_USERNAME
          WGUI_PASSWORD
          WGUI_PASSWORD_HASH
          WGUI_DNS
          EMAIL_FROM_ADDRESS
          EMAIL_FROM_NAME
          SENDGRID_API_KEY
          SMTP_HOSTNAME
          SMTP_USERNAME
          SMTP_PASSWORD
        )
        
        for i in "${env_file_vars[@]}"; do
          file_env "$i"
        done
        
        # extract wg config file path, or use default
        conf="$(jq -r .config_file_path db/server/global_settings.json || echo /etc/wireguard/wg0.conf)"
        
        # manage wireguard stop/start with the container
        case $WGUI_MANAGE_START in (1|t|T|true|True|TRUE)
            wg-quick up "$conf"
            trap 'wg-quick down "$conf"' SIGTERM # catches container stop
        esac
        
        # manage wireguard restarts
        case $WGUI_MANAGE_RESTART in (1|t|T|true|True|TRUE)
            [[ -f $conf ]] || touch "$conf" # inotifyd needs file to exist
            inotifyd - "$conf":w | while read -r event file; do
                wg-quick down "$file"
                wg-quick up "$file"
            done &
        esac
```

It's messy... but would allow others to at least use the feature without having to recompile the project or rebuild the image.

**Comment by ngoduykhanh** [comment]
Fair enough. I am merging the PR. Sorry for the late response.

**Pull request merged**
